// This file is generated by `npm run generate:api`.
// Do not edit by hand.

export type ApiSchemas = {
  "PasswordRequest": {
    "password": string;
  };
  "SessionResponse": {
    "authenticated": boolean;
    "role": "public_guest" | "enhanced_guest" | "admin";
  };
  "Player": {
    "id": string;
    "name": string;
    "createdAt": string;
    "updatedAt": string;
  };
  "AddPlayerRequest": {
    "name": string;
  };
  "PlayerResponse": {
    "player": ApiSchemas["Player"];
  };
  "ListPlayersResponse": {
    "players": ApiSchemas["Player"][];
  };
  "MatchPlayerResult": {
    "playerId": string;
    "playerName": string;
    "score": number;
    "place": number;
  };
  "AddMatchPlayerRequest": {
    "playerId": string;
    "score": number;
    "place": number;
  };
  "Match": {
    "id": string;
    "players": ApiSchemas["MatchPlayerResult"][];
    "gameType": "east" | "south";
    "gameTime": string;
    "notes"?: string | null;
    "createdAt": string;
    "updatedAt": string;
  };
  "AddMatchRequest": {
    "players": ApiSchemas["AddMatchPlayerRequest"][];
    "gameType": "east" | "south";
    "gameTime": string;
    "notes"?: string | null;
  };
  "MatchResponse": {
    "match": ApiSchemas["Match"];
  };
  "ListMatchesResponse": {
    "matches": ApiSchemas["Match"][];
  };
  "ErrorResponse": {
    "error": string;
  };
};

